import type { Metadata } from 'next'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='bg-sky-50/50 m-auto max-w-4xl'>
        {children}
        <footer className='fixed bottom-0 w-full bg-primary text-white py-2 text-center'>
          <div className='flex justify-center space-x-4'>
            <a className='hover:underline' href='#'>
              ホーム
            </a>
            <a className='hover:underline' href='#'>
              一覧
            </a>
            <a className='hover:underline' href='#'>
              設定
            </a>
          </div>
        </footer>
      </body>
    </html>
  )
}
