import { Toaster } from '@/components/ui/toaster'

import type { Metadata } from 'next'

import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Toaster />
        <div className='bg-gradient-to-b from-blue-50 to-sky-100 h-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
